# Generated by Django 2.1 on 2018-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditioning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='conditioning_notes',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='suppliment_taken',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
