# Generated by Django 2.1 on 2018-08-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20180825_0000'),
        ('conditioning', '0002_auto_20180824_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Condition',
        ),
    ]
