# Generated by Django 2.1 on 2018-08-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=225)),
                ('injury_date', models.DateField()),
                ('injury_comments', models.CharField(max_length=255)),
                ('recovery_date', models.DateField()),
                ('conditioning_notes', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
