# Generated by Django 2.1 on 2018-08-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('coach_name', models.CharField(max_length=30)),
                ('coach_contact', models.CharField(max_length=15)),
                ('team_manager', models.CharField(max_length=30)),
                ('team_manager_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='High_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=100)),
                ('patron', models.CharField(max_length=100)),
                ('patron_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('kin', models.CharField(max_length=30)),
                ('kin_contact', models.CharField(max_length=15)),
                ('passport', models.CharField(max_length=150, null=True)),
                ('allergy', models.CharField(max_length=200, null=True)),
                ('injury_history', models.CharField(max_length=15, null=True)),
                ('skills', models.CharField(max_length=15, null=True)),
                ('about_player', models.CharField(max_length=15, null=True)),
                ('tertiary_institution', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('address_contact', models.CharField(max_length=15, null=True)),
                ('id_number', models.CharField(max_length=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/players')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Role'),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.High_school'),
        ),
    ]
